### ISSUE TITLE
broadcasting strategy

### ISSUE THREAD

**Issue by kkmann** [kkmann/checkr#1]
How do we cope with lists/arrays? One might want to broadcast checks elementwise in a generic way.

**Comment by gleday** [comment]
Yes, simply elementwise. So the same types of checks have to be carried out for each component of the list.

**Comment by kkmann** [comment]
commit 88dc4c853ccd076cc37065f3bf9cba926df11b30 shoueld address that, not sure how to make it work for arrays and lists alike though...
